changing docker ignore

diff --git a/eureka-server/Jenkinsfile b/eureka-server/Jenkinsfile
--- a/eureka-server/Jenkinsfile
+++ b/eureka-server/Jenkinsfile
@@ -1,43 +1,89 @@
 pipeline {
     agent any
 
+    tools {
+        maven 'Maven-3'
+    }
+
     environment {
-        IMAGE_NAME = "eureka-server"
-        CONTAINER_NAME = "eureka-server-container"
+        GIT_REPO        = 'https://github.com/D-Rohith-Gola/Final-Case-Study.git'
+        GIT_BRANCH      = 'feature-branch'
+        IMAGE_NAME      = 'eureka-server'
+        CONTAINER_NAME  = 'eureka-server'
+        DOCKER_NETWORK  = 'admin'
+        IMAGE_TAG       = 'latest'
     }
 
     stages {
 
-        stage('Checkout') {
+        stage('Clean Workspace') {
             steps {
-                checkout scm
+                cleanWs()
             }
         }
 
-        stage('Build Jar') {
+        stage('Clone Repository') {
             steps {
-                bat 'mvn clean package -DskipTests'
+                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
             }
         }
+
+       stage('Build Application (Skip Tests)') {
+    steps {
+        dir('eureka-server') {
+            bat 'mvn clean package -DskipTests'
+        }
+    }
+}
+
 
         stage('Build Docker Image') {
+    steps {
+        dir('eureka-server') {
+            bat """
+            docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
+            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
+            """
+        }
+    }
+}
+
+
+        stage('Ensure Docker Network Exists') {
             steps {
-                bat 'docker build -t %IMAGE_NAME% .'
+                bat """
+                docker network inspect ${DOCKER_NETWORK} >nul 2>&1 || docker network create ${DOCKER_NETWORK}
+                """
             }
         }
 
-        stage('Stop Old Container') {
+        stage('Stop & Remove Existing Container If Running') {
             steps {
-                bat '''
-                docker rm -f %CONTAINER_NAME% || exit 0
-                '''
+                bat """
+                docker rm -f ${CONTAINER_NAME} >nul 2>&1 || exit 0
+                """
             }
         }
 
         stage('Run New Container') {
             steps {
-                bat 'docker run -d -p 8761:8761 --name %CONTAINER_NAME% %IMAGE_NAME%'
+                bat """
+                docker run -d ^
+                    --name ${CONTAINER_NAME} ^
+                    --network ${DOCKER_NETWORK} ^
+                    -p 8761:8761^
+                    ${IMAGE_NAME}:latest
+                """
             }
+        }
+    }
+
+    post {
+        success {
+            echo "Deployment Successful 🚀"
+        }
+        failure {
+            echo "Deployment Failed ❌"
         }
     }
 }
